{
	"version": 1596632968,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/logo_empresa-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/voltar-sheet0.png",
		"images/botãoj1-sheet0.png",
		"images/botãoj2-sheet0.png",
		"images/botãoj3-sheet0.png",
		"images/botãoj4-sheet0.png",
		"images/botãoj5-sheet0.png",
		"images/carta-sheet0.png",
		"images/árvore-sheet0.png",
		"images/placas-sheet0.png",
		"images/placas-sheet1.png",
		"images/placas-sheet2.png",
		"images/placa-sheet0.png",
		"images/conversa2-sheet0.png",
		"images/conversa1-sheet0.png",
		"images/conversa3-sheet0.png",
		"images/conversa4-sheet0.png",
		"images/conversa5-sheet0.png",
		"images/conversa6-sheet0.png",
		"images/conversa7-sheet0.png",
		"images/conversa8-sheet0.png",
		"images/conversa9-sheet0.png",
		"images/conversa10-sheet0.png",
		"images/conversa11-sheet0.png",
		"images/conversa12-sheet0.png",
		"images/conversa13-sheet0.png",
		"images/conversa14-sheet0.png",
		"images/conversa15-sheet0.png",
		"images/conversa16-sheet0.png",
		"images/peca-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/moddelo-sheet0.png",
		"images/sensor-sheet0.png",
		"images/pecafase2-sheet0.png",
		"images/pecafase2-sheet1.png",
		"images/pecafase2-sheet2.png",
		"images/modelo-sheet0.png",
		"images/sensorp-sheet0.png",
		"images/sprite-sheet0.png",
		"images/cobrir-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/grandpa-sheet0.png",
		"images/grandma-sheet0.png",
		"images/grandfather-sheet0.png",
		"images/grandmother-sheet0.png",
		"images/uncle-sheet0.png",
		"images/father-sheet0.png",
		"images/mother-sheet0.png",
		"images/aunt-sheet0.png",
		"images/sister-sheet0.png",
		"images/brother-sheet0.png",
		"images/cousin-sheet0.png",
		"images/me-sheet0.png",
		"images/ar-sheet0.png",
		"images/linha-sheet0.png",
		"images/fotomouse-sheet0.png",
		"images/teclado-sheet0.png",
		"media/anything.m4a",
		"media/anything.ogg",
		"media/aunt.m4a",
		"media/aunt.ogg",
		"media/be fine.m4a",
		"media/be fine.ogg",
		"media/brother.m4a",
		"media/brother.ogg",
		"media/but.m4a",
		"media/but.ogg",
		"media/come in.m4a",
		"media/come in.ogg",
		"media/cousin.m4a",
		"media/cousin.ogg",
		"media/dancer.m4a",
		"media/dancer.ogg",
		"media/dentist.m4a",
		"media/dentist.ogg",
		"media/doctor.m4a",
		"media/doctor.ogg",
		"media/excuseme.m4a",
		"media/excuseme.ogg",
		"media/father.m4a",
		"media/father.ogg",
		"media/film-makker.m4a",
		"media/film-makker.ogg",
		"media/grandma.m4a",
		"media/grandma.ogg",
		"media/grandmother.m4a",
		"media/grandmother.ogg",
		"media/grandpa.m4a",
		"media/grandpa.ogg",
		"media/journalist.m4a",
		"media/journalist.ogg",
		"media/me.m4a",
		"media/me.ogg",
		"media/monther.m4a",
		"media/monther.ogg",
		"media/musici.m4a",
		"media/musici.ogg",
		"media/no i'm not.m4a",
		"media/no i'm not.ogg",
		"media/now i1m going.m4a",
		"media/now i1m going.ogg",
		"media/programmer.m4a",
		"media/programmer.ogg",
		"media/relax.m4a",
		"media/relax.ogg",
		"media/see u latter.m4a",
		"media/see u latter.ogg",
		"media/see ya.m4a",
		"media/see ya.ogg",
		"media/sister.m4a",
		"media/sister.ogg",
		"media/so.m4a",
		"media/so.ogg",
		"media/tanks for the words.m4a",
		"media/tanks for the words.ogg",
		"media/teacher.m4a",
		"media/teacher.ogg",
		"media/today have.m4a",
		"media/today have.ogg",
		"media/traffic cup.m4a",
		"media/traffic cup.ogg",
		"media/uncle.m4a",
		"media/uncle.ogg",
		"media/what happ.m4a",
		"media/what happ.ogg",
		"media/you ara okay.m4a",
		"media/you ara okay.ogg",
		"media/you very stu.m4a",
		"media/you very stu.ogg",
		"media/grandfather.m4a",
		"media/grandfather.ogg",
		"media/chemical.m4a",
		"media/chemical.ogg",
		"media/som de tic tac de relógio - Ótimo para ativar seu sono- dormir e relaxar.m4a",
		"media/fundo.m4a",
		"media/fundo.ogg",
		"media/jogo4.m4a",
		"media/jogo4.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}